<a href="https://colab.research.google.com/github/faisal-rasheed-lone/100-python-projects/blob/master/NumPy_Practice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
arr = np.array([[2,3,4],[5,6,8],[1,0,3]])

In [4]:
print(arr)

[[2 3 4]
 [5 6 8]
 [1 0 3]]


#Creating array using other functions


In [5]:
arr1 = np.zeros((2,3))

In [6]:
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
arr2 = np.ones((2,3))

In [8]:
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
arr3 = np.empty((2,3), dtype = int)
print(arr3)

[[4607182418800017408 4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408]]


In [10]:
print(arr3.shape)

(2, 3)


In [11]:
print(arr3.size)

6


In [12]:
arr4 = np.arange(2,10,2)
print(arr4)
print(arr4)

[2 4 6 8]
[2 4 6 8]


In [13]:
print(np.linspace(1,10,5))

[ 1.    3.25  5.5   7.75 10.  ]


In [14]:
print(np.add(arr2, arr2))

[[2. 2. 2.]
 [2. 2. 2.]]


In [15]:
print(arr1 + arr1)

[[0. 0. 0.]
 [0. 0. 0.]]


#Indexing and Slicing

In [16]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [17]:
print(arr1[1:])

[[4 5 6]
 [7 8 9]]


In [18]:
matrix = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])

In [19]:
#What is the value at row 2, column 3?
print(matrix[1, 2])

70


In [20]:
#Extract the 3rd row as a 1D array.
oneD = matrix[2, :]
print(oneD)

[ 90 100 110 120]


In [21]:
#Extract the 2nd column as a 1D array.
print(matrix[:, 1])

[ 20  60 100 140]


In [22]:
#Extract a 2x2 subarray from the bottom-right corner of the matrix.
print(matrix[2:, 2:])

[[110 120]
 [150 160]]


In [23]:
# Extract every alternate element from the 2nd row.
print(matrix[1, 0:4:2])

[50 70]


In [24]:
#Reverse the order of rows in the matrix.
print(matrix[::-1, :])

[[130 140 150 160]
 [ 90 100 110 120]
 [ 50  60  70  80]
 [ 10  20  30  40]]


In [25]:
# Reverse the order of columns in the matrix.
print(matrix[:, ::-1])

[[ 40  30  20  10]
 [ 80  70  60  50]
 [120 110 100  90]
 [160 150 140 130]]


In [26]:
#Extract elements from rows 1 and 3 and columns 2 and 4.
print(matrix[[0,2], [1,3]])

[ 20 120]


In [27]:
#Extract all elements greater than 50.
print(matrix[matrix > 50])

[ 60  70  80  90 100 110 120 130 140 150 160]


In [28]:
#Extract the values at positions (0, 1), (2, 3), and (3, 0).
print(matrix[[0,2,3],[1,3,0]])

[ 20 120 130]


In [29]:
matrix = np.array([
    [5, 10, 15, 20],
    [25, 30, 35, 40],
    [45, 50, 55, 60],
    [65, 70, 75, 80]
])

What is the value at row 3, column 4?

In [30]:
print(matrix[2, 3])

60


Extract the first two rows as a subarray.

In [31]:
print(matrix[:2, :])

[[ 5 10 15 20]
 [25 30 35 40]]


Extract the last two columns as a subarray.

In [32]:
print(matrix[:, 2:])

[[15 20]
 [35 40]
 [55 60]
 [75 80]]


Extract a 2x3 subarray consisting of rows 2 and 3 and columns 1 2,and 3


In [33]:
print(matrix[1:3, 0:3])

[[25 30 35]
 [45 50 55]]


Extract elements from row 1, column 4 and row 4, column 2.

In [34]:
print(matrix[[0,3],[3,1]])

[20 70]


Find all elements that are divisible by 10.

In [35]:
print(matrix[matrix % 10 == 0])

[10 20 30 40 50 60 70 80]


Extract the 1st and 4th rows.

In [36]:
print(matrix[[0,3], :])

[[ 5 10 15 20]
 [65 70 75 80]]


 Extract the 2nd and 3rd columns.

In [37]:
print(matrix[:, [1,2]])

[[10 15]
 [30 35]
 [50 55]
 [70 75]]


 Reverse the rows and columns in the matrix.

In [38]:
print(matrix[::-1 ,::-1])

[[80 75 70 65]
 [60 55 50 45]
 [40 35 30 25]
 [20 15 10  5]]


Extract every alternate element in the last row.

In [39]:
print(matrix[3, 0::2])

[65 75]


Reshape the array np.array([1, 2, 3, 4, 5, 6, 7, 8]) into a 2x4 matrix.

In [40]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr.shape)

(8,)


In [41]:
reshaped = arr.reshape(2,4)
print(reshaped)

[[1 2 3 4]
 [5 6 7 8]]


Flatten the Array


In [42]:
#print(reshaped.flatten())

Concatenation


In [43]:
print(np.concatenate((matrix, reshaped), axis = 0))

[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]
 [65 70 75 80]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [44]:
print(matrix)
matrix1 = matrix[::-1, ::-1]
print(matrix1)

[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]
 [65 70 75 80]]
[[80 75 70 65]
 [60 55 50 45]
 [40 35 30 25]
 [20 15 10  5]]


Stacking Arrays


In [45]:
print(np.hstack((matrix, matrix1)))

[[ 5 10 15 20 80 75 70 65]
 [25 30 35 40 60 55 50 45]
 [45 50 55 60 40 35 30 25]
 [65 70 75 80 20 15 10  5]]


In [46]:
print(np.vstack((matrix1, matrix)))

[[80 75 70 65]
 [60 55 50 45]
 [40 35 30 25]
 [20 15 10  5]
 [ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]
 [65 70 75 80]]


In [47]:
print(np.dstack((matrix1, matrix)))

[[[80  5]
  [75 10]
  [70 15]
  [65 20]]

 [[60 25]
  [55 30]
  [50 35]
  [45 40]]

 [[40 45]
  [35 50]
  [30 55]
  [25 60]]

 [[20 65]
  [15 70]
  [10 75]
  [ 5 80]]]


#Spltting Arrays

In [48]:
split_arr = np.split(matrix, (2,4))
print(split_arr)

[array([[ 5, 10, 15, 20],
       [25, 30, 35, 40]]), array([[45, 50, 55, 60],
       [65, 70, 75, 80]]), array([], shape=(0, 4), dtype=int64)]


In [49]:
arr1 = np.ones((3,3))
print(arr1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [50]:
print(np.vsplit(arr1, 3))

[array([[1., 1., 1.]]), array([[1., 1., 1.]]), array([[1., 1., 1.]])]


In [51]:
#Reverse both rows and columns of the array:
arr = np.array([[1,2],[3,4],[5,6]])
print(arr[::-1, ::-1])

[[6 5]
 [4 3]
 [2 1]]


In [52]:
test = np.array([1,2,3,4,5,6])
print(np.reshape(test, (2,3)))

[[1 2 3]
 [4 5 6]]


In [53]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
concatenated = np.concatenate((arr1, arr2), axis=1)
print(concatenated)
# Output:
# [[1 2 5 6]
#  [3 4 7 8]]

[[1 2 5 6]
 [3 4 7 8]]


**Transpose the matrix:**

In [54]:
arr = np.array([[10, 20], [30, 40], [50, 60]])
print(arr)
print(arr.T)

[[10 20]
 [30 40]
 [50 60]]
[[10 30 50]
 [20 40 60]]


**Tile the array**

In [55]:
arr = np.array([1, 2, 3])
print(np.tile(arr, 3))

[1 2 3 1 2 3 1 2 3]


Repeat each element

In [56]:
print(np.repeat(arr, 2))

[1 1 2 2 3 3]


Sorting Array Row Wise

In [57]:
arr = np.array([10,3,5,6,8])
print(np.sort(arr))

[ 3  5  6  8 10]


In [58]:
arr1 = np.array([[9, 1, 3], [7, 6, 5]])
print(np.sort(arr1, axis = 0))

[[7 1 3]
 [9 6 5]]


In [63]:
#Computing Inverse
arr = np.array([[2,3],[5,6]])
print(np.linalg.inv(arr))

[[-2.          1.        ]
 [ 1.66666667 -0.66666667]]


Mathematical Operations
Compute the product of all elements in the array:

In [64]:
arr = np.array([1, 2, 3, 4])
print("product = ",np.prod(arr))

product =  24


In [66]:
#Find the cosine of each element in the array:
arr = np.array([0, np.pi/4, np.pi/2])
print("Cosine of arr[2] = ", np.sin(arr[2]))

Cosine of arr[2]  1.0


Compute the dot product of these arrays:
np.array([1, 2, 3]) and np.array([4, 5, 6]).

In [67]:
arr1 =  np.array([1, 2, 3])
arr2 = np.array([4,5,6])
print("Dot product = ", np.dot(arr1, arr2))

Dot product =  32


Perform matrix multiplication between:

In [68]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
print("Mat Mul  = ", np.matmul(mat1, mat2))

Mat Mul  =  [[19 22]
 [43 50]]


Find the determinant of this matrix:

In [69]:
arr = np.array([[2, 3], [1, 4]])
print("determinant = ", np.linalg.det(arr))

determinant =  5.000000000000001


Find the standard deviation of this array:

In [70]:
arr = np.array([1, 2, 3, 4, 5])
print("Standard deviation = ", np.std(arr))

Standard deviation =  1.4142135623730951


Compute the 90th percentile for this array:

In [71]:
arr = np.array([10, 20, 30, 40, 50])
print('90th percentile = ', np.percentile(arr, 90))

90th percentile =  46.0


Generate a 4x4 matrix of random numbers from a uniform distribution.

In [77]:
arr = np.random.uniform(0, 100, size= (3, 3))
print(arr)

[[74.59044429 50.23089538 90.4822694 ]
 [45.67523409 64.76704831 76.02239923]
 [58.81608437 32.27174098 56.7237713 ]]


Create 10 random integers between 100 and 200.

In [80]:
arr = np.random.randint(40, 80, size = (10))
print(arr)

[72 72 61 46 78 48 71 54 49 63]


Sample 6 numbers from a normal distribution with mean 5 and std 1.

In [82]:
print(np.random.normal(5, 1, size = (6)))

[4.3806762  6.02849599 3.05393069 5.58179978 4.44741418 4.05635417]


Generate random numbers from a binomial distribution with 15 trials and probability 0.7.

In [83]:
print(np.random.binomial(15, 0.7, size = (2,3)))

[[10 10 11]
 [12  9 10]]


Add a scalar value of 5 to each element in a 3x3 matrix.

In [86]:
arr = np.random.randint(3,15 , size = (3,3))
print(arr)
print(arr + 5)

[[ 3  4  3]
 [10  3  7]
 [ 4  5  7]]
[[ 8  9  8]
 [15  8 12]
 [ 9 10 12]]


Multiply each row of a 2x3 matrix by a 1D array of shape (3,)

In [92]:
arr = np.random.randint(10,20, size = (2,3))
arr1 = np.random.randint(2,8, size = (2, 3))

result = arr * arr1
print(result)

[[78 60 48]
 [84 33 57]]


Given arr = np.array([5, 10, 15, 20]), select elements at indices [1, 3].

In [96]:
arr = np.array([5, 10, 15, 20])
print(arr[[0,2]])

[ 5 15]


Extract all even numbers from a 1D array.

In [97]:
arr = np.array([5, 10, 15, 20])
print("All even Numbers = ", arr[arr % 2 == 0])

All even Numbers =  [10 20]


Modify all negative numbers in a 2D array to 0.

In [107]:
arr = np.arange(-5, 4, dtype = int)
arr = np.arange(-5, 4, dtype = int)
arr = arr.reshape(3,3)
print(arr)
arr[arr < 0 ] = 0
print(arr)

[[-5 -4 -3]
 [-2 -1  0]
 [ 1  2  3]]
[[0 0 0]
 [0 0 0]
 [1 2 3]]


Sort the rows of a 3x3 matrix.
Given arr = np.array([8, 3, 7, 4]), return the indices of elements in sorted order.

In [109]:
arr = np.random.randint(10, 20, size = (3,3))
print(arr)
print(np.sort(arr, axis = 1))

[[17 19 11]
 [15 15 12]
 [16 12 10]]
[[11 17 19]
 [12 15 15]
 [10 12 16]]


In [112]:
arr = np.array([8, 3, 7, 4])
print(np.sort(arr, axis = 0))
print(np.argsort(arr))

[3 4 7 8]
[1 3 2 0]


In [114]:
print(np.where(arr > 5))

(array([0, 2]),)


Find the indices where elements are greater than 10 in

In [116]:
arr = np.array([5, 15, 10, 20])
print(np.where(arr > 10))

(array([1, 3]),)


Find unique elements and their counts in:

In [118]:
arr = np.array([5, 5, 10, 15, 10, 10])
print(np.unique(arr, return_counts = True))
print(np.bincount(arr))

(array([ 5, 10, 15]), array([2, 3, 1]))
[0 0 0 0 0 2 0 0 0 0 3 0 0 0 0 1]
